name: release

# on:
#   push:
#     tags:
#       - v[0-9]+.[0-9]+.[0-9]+
on:
  workflow_run:
    workflows: ["CI"]
    push:
      tags: 
        - v[0-9]+.[0-9]+.[0-9]+
    types:
      - completed

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.1"
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go test ./...
      # - uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage.out
      - uses: goreleaser/goreleaser-action@v4
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update doc
        run: curl https://proxy.golang.org/github.com/axpira/gt/@v/${GITHUB_REF_NAME}.info
